name: affiliateo
description: Mobile affiliate attribution and session tracking for Flutter apps.
version: 1.0.0
homepage: https://affiliateo.com
repository: https://github.com/NicoGrajales/affiliateo-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  device_info_plus: ^9.0.0
  package_info_plus: ^5.0.0
  shared_preferences: ^2.2.0
